version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:01"
      timezone: "America/Sao_Paulo"
    cooldown:
      default-days: 7
      semver-minor-days: 7
      semver-patch-days: 3
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    groups:
      dependencies:
        patterns:
          - "*"
